name: workflow.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run tests
        run: mvn clean test

      - name: Generate report
        run: mvn surefire-report:report

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: target/site/

      - name: Upload test results (XML)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/